import Head from 'next/head'
import HeaderNavBar from '../components/HeaderNavBar'
import MainPlanText from '../components/MainPlanText'
import PlanPrices from '../components/PlanPrices'
import Plans from '../components/Plans'

export default function Home() {
  return (
    <>
      <Head>
        <title>DocHQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderNavBar/>
        <MainPlanText/>
        <Plans/>
        <PlanPrices/>
      </main>
    </>
  )
}
